//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedUser
    {
        public int id { get; set; }
        public string faculty_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int user_type { get; set; }
    }
}
