//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int announcementID { get; set; }
        public string announcementMsg { get; set; }
        public System.DateTime expiryDate { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int status { get; set; }
        public int createdBy { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
