//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelledClassSchedule
    {
        public int cancelled_id { get; set; }
        public int schedID { get; set; }
        public System.DateTime cancelledDate { get; set; }
        public string subjectCode { get; set; }
        public string section { get; set; }
        public string facultyName { get; set; }
        public string room { get; set; }
        public Nullable<System.DateTime> dateFiled { get; set; }
        public string time { get; set; }
        public string numHours { get; set; }
        public string reason { get; set; }
    }
}
