//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentSetting
    {
        public int ID { get; set; }
        public string semester { get; set; }
        public short schoolYearStart { get; set; }
        public short schoolYearEnd { get; set; }
        public System.DateTime durationStart { get; set; }
        public System.DateTime durationEnd { get; set; }
        public int modifiedBy { get; set; }
        public System.DateTime dateModified { get; set; }
    }
}
