//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakeupClassSchedule
    {
        public int makeupClassID { get; set; }
        public System.DateTime absentDate { get; set; }
        public string subjectCode { get; set; }
        public string faculty_id { get; set; }
        public string facultyName { get; set; }
        public string section { get; set; }
        public System.DateTime dateFiled { get; set; }
        public System.DateTime makeupDate { get; set; }
        public string room { get; set; }
        public string time { get; set; }
        public string numHours { get; set; }
        public string reason { get; set; }
        public Nullable<int> approvedBy { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string remarks { get; set; }
        public string semester { get; set; }
        public Nullable<int> schoolYearStart { get; set; }
        public Nullable<int> schoolYearEnd { get; set; }
    }
}
