//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messaging
    {
        public int msgID { get; set; }
        public int author { get; set; }
        public int receiver { get; set; }
        public string subject { get; set; }
        public string sender_receiver_datetime { get; set; }
        public Nullable<int> sender { get; set; }
        public string sender_message { get; set; }
        public Nullable<System.DateTime> sent_datetime { get; set; }
        public System.DateTime author_sentdatetime { get; set; }
        public Nullable<int> isInbox { get; set; }
        public Nullable<int> isInArchive { get; set; }
        public Nullable<int> isInTrash { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<int> isRead { get; set; }
    }
}
