//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThesisDBEntities : DbContext
    {
        public ThesisDBEntities()
            : base("name=ThesisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllowedUser> AllowedUsers { get; set; }
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<CancelledClassSchedule> CancelledClassSchedules { get; set; }
        public DbSet<CurrentSetting> CurrentSettings { get; set; }
        public DbSet<ForgotPasswordTicket> ForgotPasswordTickets { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<MakeupClassSchedule> MakeupClassSchedules { get; set; }
        public DbSet<Messaging> Messagings { get; set; }
        public DbSet<OpenTime> OpenTimes { get; set; }
        public DbSet<PE_RoomList> PE_RoomList { get; set; }
        public DbSet<PendingClassSchedule> PendingClassSchedules { get; set; }
        public DbSet<RoomList> RoomLists { get; set; }
        public DbSet<SemesterSchedule> SemesterSchedules { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
