//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingClassSchedule
    {
        public int pendingClassID { get; set; }
        public System.DateTime absentDate { get; set; }
        public string subjectCode { get; set; }
        public string section { get; set; }
        public string faculty_id { get; set; }
        public string facultyName { get; set; }
        public System.DateTime dateFiled { get; set; }
        public System.DateTime assignedDate { get; set; }
        public string room { get; set; }
        public string duration { get; set; }
        public string numHours { get; set; }
        public string reason { get; set; }
    }
}
