//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterSchedule
    {
        public int schedID { get; set; }
        public string roomNumber { get; set; }
        public string days { get; set; }
        public string subjectCode { get; set; }
        public string section { get; set; }
        public string instructor { get; set; }
        public string numofHours { get; set; }
        public int semester { get; set; }
        public int schoolYearStart { get; set; }
        public int schoolYearEnd { get; set; }
        public System.DateTime durationStart { get; set; }
        public System.DateTime durationEnd { get; set; }
        public string hasMonday { get; set; }
        public string hasTuesday { get; set; }
        public string hasWednesday { get; set; }
        public string hasThursday { get; set; }
        public string hasFriday { get; set; }
        public string hasSaturday { get; set; }
        public string time { get; set; }
    }
}
