//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string faculty_id { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email_address { get; set; }
        public System.DateTime date_created { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<bool> status { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> user_type { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
